### ISSUE TITLE
Not working... install seems to execute without problems - No Lucee instance running 

### ISSUE THREAD

**Issue by wgregori** [foundeo/ubuntu-nginx-lucee#15]
Thanks for all the work on these install scripts but my resulting system is not a working Lucee install.  The lucee server.cfm page results in a 404 error.  I've gone through the install twice on an Ubuntu 14.04 server with the same results.  When I grep Lucee I find no live instances of it running.  
ps au | grep lucee

Any ideas?
Wayne

**Comment by pfreitag** [comment]
Hi Wayne - you will not find `lucee` in the ps list, it uses the Tomcat that ships with Ubuntu so grep for `tomcat` or `java`

**Comment by wgregori** [comment]
okay... perhaps you can help me debug this.  It appears that Lucee may not be completely installed. 
trying to find 'server.cfm' results in nothing found.

root@ubuntu:/# find / -name 'server.cfm'
root@ubuntu:/#

I don't think that root directory has been installed.  However, I do see the lucee.conf in the nginx directory.

Thanks for any direction you might offer.

**Comment by wgregori** [comment]
more info on my install.  my web  root does not have Lucee directories...
root@ubuntu:/web# ls
default  example.com

that seems like a problem

**Comment by wgregori** [comment]
Solved my problem... I edited the install.sh script to remove the Lucee install.  I then ran your foundeo install script then downloaded Lucee 5 and proceeded with an install.  Worked.  Thanks

**Comment by claytondus** [comment]
@wgregori Wayne, there were a few other items I needed to do before I could log in to the Lucee admin.

1. The default nginx site (/etc/nginx/sites-available/default.conf) did not have "include lucee.conf;" so CFML requests were not being redirected to tomcat.

2. The reason you could not see the Lucee admin files was because they are created on first access to the context.  The ROOT context is owned by root instead of tomcat7, this needs to be changed so that tomcat can create the Lucee context:
chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/ROOT

From here I was able to hit http://localhost/lucee/admin/server.cfm.

**Comment by joshuairl** [comment]
Geez, I'm having a terrible time... Ubuntu 16, Tomcat 7, Lucee 5.1 ... same issues but can't get it resolved.

**Comment by wgregori** [comment]
I have used this script to install but I'm afraid that the Lucee install segment has not worked.  I have commented out the Lucee install lines then run the edited install script.  Then download Lucee (I'm installing 5.0.0.34). During the install for Lucee when asked to link to Apache respond No.  Once the install incomplete and you've changed the ip in /etc/nginx/conf/lucee.conf then login with http:yourIP:8888

good luck

**Comment by pfreitag** [comment]
Hi Folks,

I've made a bunch of updates to the script yesterday to resolve the Lucee 5 / Ubuntu 16 issues. As such I think this ticket can be closed as a few contributions broke some things.

The `default.conf` does not include `lucee.conf` on purpose, the default site is a good catch all for bad bots / script kiddies since it listens on the IP addresses.
