### ISSUE TITLE
No WEB-INF directory created

### ISSUE THREAD

**Issue by brianharcourt** [foundeo/ubuntu-nginx-lucee#25]
First, thank you Mr. Freitag!  This script saved me a lot of time!

I'm accustomed to using Web.cfc in WEB-INF/lucee/context/ to load some server variables.   But it seems that with the web.xml settings putting the lucce-web-directory in /opt/lucee/config/web - I'm not seeing WEB-INF being created anywhere.   Does this make sense or am I way off base?

I've tried placing a Web.cfc in various places but no server vars seem to get set on server restarts.

The Web.cfc contains something like this:
```
component {
     public function onWebStart() {
	server.server_name = "IL1LBIBISON09";
	server.dsn = "LBDataHub";
	server.farmserver = "BISON09";
	server.devserver = FALSE;
	server.appRoot = "/vol1/clips/";
    }
}
```
Is there some other place that runs `onWebStart()`?

**Comment by pfreitag** [comment]
Hi @brianharcourt 

I have not used the `Web.cfc` file personally, but based on what I can find you would need to place it under:

`/opt/lucee/config/web/{{web-id}}/context`

The setup scripts do keep the `WEB-INF` out of the web root on purpose, this is where it tells Lucee to use `/opt/lucee/config` instead of automatically putting in the web root: https://github.com/foundeo/ubuntu-nginx-lucee/blob/master/etc/tomcat8/web.xml#L67-L71

You can edit your `/etc/tomcat8/web.xml` file to comment out those lines and it should revert to putting `WEB-INF` in the web root again.

**Comment by brianharcourt** [comment]
Right - I saw that in the web.xml - love it!  But I did drop a Web.cfc in that directory and it didn't seem to work.  Having said that there was a lot of shuffling going on.  Now that you've confirmed what I'd been thinking - I'll carefully walk thru some tests again.  

Out of curiosity, what are you looking at when you're trying to see where a `Web.cfc` would be lodaded?  I did search the Lucee GitHub and found this:
https://github.com/lucee/Lucee/blob/5.2.2/core/src/main/java/lucee/runtime/config/XMLConfigWebFactory.java#L290-L291

I'm so low on the learning curve I couldn't really trace this back to an understanding of where `Web.cfc` would be expected.  If my tests of putting it in `/opt/lucee/config/web{{web-id}}/context` don't yield the results I want I'm guessing I'll dig further here. Or would you suggest I dig elsewhere?

At anyrate, thank you again for the info.  I'll dig around and report back what I find.

**Comment by brianharcourt** [comment]
To close the loop; `/opt/lucee/config/web/{{web-id}}/context' *is* the correct place to put the file.   I didn't isolate the variables but success came after:
- case sensitive file name; use "Web.cfc"
- file to be owned by `tomcat8:tomcat8`

Thanks again!!
